### ISSUE TITLE
css changes not working

### ISSUE THREAD

**Issue by jazdown** [sky-bones/nanowrimo#15]
changes in html file showing up in jekyll preview and live site
css changes not previewing or appearing in live site
![screen shot 2016-02-22 at 1 46 47 pm](https://cloud.githubusercontent.com/assets/6373208/13229689/27a7f15e-d970-11e5-8b9a-4cab262c4adf.png)
![screen shot 2016-02-22 at 1 47 08 pm](https://cloud.githubusercontent.com/assets/6373208/13229688/27a79c86-d970-11e5-8c78-dcfc733f4534.png)
![screen shot 2016-02-22 at 1 47 20 pm](https://cloud.githubusercontent.com/assets/6373208/13229690/27a850d6-d970-11e5-8375-6c8c90469312.png)

**Comment by sky-bones** [comment]
(Resolved, Internal issue)
