### ISSUE TITLE
Colouring 

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#17]
- [x] Navigation (Log In)  
- [x] Profile 
- [x] Homepage
- [x] Blog (search / main) 
- [x] Prep Page
- [x] Shop (optional)

**Comment by valeriebordeleau** [comment]
@sky-bones Would this include anything other than the .ai doc? I'll put it in drive

**Comment by sky-bones** [comment]
@valeriebordeleau No, just the .ai is fine! (once it's uploaded can you share a link in the chat?)

**Comment by valeriebordeleau** [comment]
Will do. Im just working on the optional shop page.

**Comment by valeriebordeleau** [comment]
There are a few illustration assets still missing so they'll be left as boxes. @heathermcd12 is working on those.

**Comment by valeriebordeleau** [comment]
wireframe in dropbox 
https://drive.google.com/drive/folders/0BzSy8q2Q0rMFODBRVlY1SElKdnc

**Comment by sky-bones** [comment]
Add: 
- [x] Donate 
- [ ] OPTIONAL: Payment Info

**Comment by valeriebordeleau** [comment]
https://drive.google.com/drive/folders/0BzSy8q2Q0rMFODBRVlY1SElKdnc
