### ISSUE TITLE
Skip Links on Resource Page

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#18]
- [x] Link in header / footer 
- [x] Add in skip links 
- [x] Add images and text (refer to the style tiles and resources) 
- [ ](BONUS) The external links should exist, and if there are links to these documents it would be easy to match it up. 

Content: 
https://docs.google.com/document/d/1AFsAJj1bDQFTYl2Xhd5RB5F34K4RaYK1dTfrb7f2QWo/edit?usp=sharing

**Comment by valeriebordeleau** [comment]
I used the content from the prep page and cleaned up the grammar/ excessive use of dot dot dot. Is that ok content-wise?

**Comment by valeriebordeleau** [comment]
Also I'll have to ask @jamie-smith8 about the skiplinks. They're in the default layout but commented out I believe? Is it possible to make a second layout with skiplinks? This will need if statements to swap out the content

**Comment by jamie-smith8** [comment]
new layout with skip links is called skip-link.html   (too obvious?)

**Comment by valeriebordeleau** [comment]
ok.. I'll use it once I merge in in the am. IDK how to change that content though, is that an if statement?
