### ISSUE TITLE
Jekyll not working when live?

### ISSUE THREAD

**Issue by jamie-smith8** [sky-bones/nanowrimo#2]
As discussed in Facebook group. Unsure why jekyll stops working when on http://sky-bones.github.io/nanowrimo/ 

![screenshot 2016-02-08 12 21 19](https://cloud.githubusercontent.com/assets/6372772/12893334/80bea6c4-ce5e-11e5-86b0-7e88bd993700.png)
![screenshot 2016-02-08 12 21 30](https://cloud.githubusercontent.com/assets/6372772/12893337/8670ccbe-ce5e-11e5-8a82-5bb1f71ccd1b.png)

**Comment by sky-bones** [comment]
We Fixed It!
