### ISSUE TITLE
Illustrations 

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#20]
new discussed in chat - Pantser and Planner
![12421805_10153434698631149_1985764071_n](https://cloud.githubusercontent.com/assets/6333963/13377186/2468db1a-dd9f-11e5-96c8-a0fa16014cde.jpg)

Different colour schemes for icons (some are suggested on the colour wireframes)  

(Finish for Monday evening / Tuesday Morning)

**Comment by jamie-smith8** [comment]
@heathermcd12 are there new icons to choose from?

**Comment by sky-bones** [comment]
@jamie-smith8 (she's moving today, but they'll be done asap)
