### ISSUE TITLE
Polish (Header / Footer)

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#21]
(These can be finished at a later date or when you have time. They MUST be completed by March 12th (ALSO IT'S ASSIGNING THINGS WEIRDLY????) 

**Header**
- [x] Navigation - Fix the weird space, and talk to Tiffany (or make an issue) about solving the Tiny Plus
  <img width="177" alt="screen shot 2016-02-27 at 10 23 56 pm" src="https://cloud.githubusercontent.com/assets/6333963/13377251/d26b1dc6-dda0-11e5-83be-dba1048deb30.png">
- [x] Navigation - Can we lower this a tiny bit? (To the best of yr ability) 
  <img width="148" alt="screen shot 2016-02-27 at 10 25 26 pm" src="https://cloud.githubusercontent.com/assets/6333963/13377256/16df2466-dda1-11e5-8567-67e880150cf0.png">
- [x] _Tablet View / Mobile_ Smaller, take up less space. (consult design team if issues arise that are weird) 
  <img width="829" alt="screen shot 2016-02-27 at 10 27 13 pm" src="https://cloud.githubusercontent.com/assets/6333963/13377261/51adf946-dda1-11e5-965a-47efce3943c4.png">
- [x] Can the donate / join icon buckets have a bigger focus / click range for mobile/tablet? (Small concern) 

**Footer**
- [x] Logo!!!!! (condensed version)  On mobile sizes, it's been removed. 
- [x] Link text needs to be sized up to about 14-16px
  <img width="118" alt="screen shot 2016-02-27 at 10 35 36 pm" src="https://cloud.githubusercontent.com/assets/6333963/13377291/7746907c-dda2-11e5-8808-e050e4df35aa.png">
- [x] _Posibility_ Have the social media icons in one line on large sizes (if possible)

**Comment by jamie-smith8** [comment]
on it
