### ISSUE TITLE
Adding content to Homepage

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#23]
- [x] Get to know Us 
- [x] Join us (links to log in page)
- [x] Testimonial  Carousel 
- [x] Info into carousel 
- [x] Images for carousel ( @valeriebordeleau )
- [x] Press Release info
- [x] Values

**Comment by jamie-smith8** [comment]
press release and values needed.

**Comment by sky-bones** [comment]
adding them today on branch: homepage-2
