### ISSUE TITLE
Footer Links

### ISSUE THREAD

**Issue by jamie-smith8** [sky-bones/nanowrimo#31]
- [x] footer links need to go somewhere. 
  **(footer links for the default layout are in there - missing the classes to make them look good)**
- [x] class for links

**Comment by sky-bones** [comment]
Can board of directors be one line? 

<img width="109" alt="screen shot 2016-03-05 at 3 11 47 pm" src="https://cloud.githubusercontent.com/assets/6333963/13550141/9e64dbe0-e2e4-11e5-805d-392ca6d2e79b.png">

Also 'Profile' is in the links twice! (if the second one is removed it fucks up the order)

<img width="224" alt="screen shot 2016-03-05 at 3 20 32 pm" src="https://cloud.githubusercontent.com/assets/6333963/13550179/cfb35c3e-e2e5-11e5-9d5e-617a63f3502a.png">
