### ISSUE TITLE
Homepage Links

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#35]
I'd like to center it on small screens eventually - a minor worry

<img width="547" alt="screen shot 2016-03-05 at 3 00 49 pm" src="https://cloud.githubusercontent.com/assets/6333963/13550075/117ca434-e2e3-11e5-906d-4af0fb892364.png">

**Comment by jamie-smith8** [comment]
I will fix it tomorrow :)

**Comment by jamie-smith8** [comment]
donnneeeee
