### ISSUE TITLE
Homepage - Press Release info

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#53]
On mobile (tested on iphone 5 and android phone) 
Idk about the links - but the spacing could be a TOUCH better

![12810346_10205822024405246_1807485323_o](https://cloud.githubusercontent.com/assets/6333963/13705287/26f6c2b0-e76e-11e5-9843-6a464e707fa8.jpg)

**Comment by jamie-smith8** [comment]
things were in media queries that were NOT supposed to be
