### ISSUE TITLE
Carousel code

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#6]
This code would be used on ALL pages with a carousel on it. It needs to work for the three screen sizes, and have a max of 8-12 entries.

<img width="105" alt="screen shot 2016-02-20 at 3 15 32 pm" src="https://cloud.githubusercontent.com/assets/6333963/13198952/defdb0a6-d7e4-11e5-9880-3d7d2295335f.png">
<img width="215" alt="screen shot 2016-02-20 at 3 15 27 pm" src="https://cloud.githubusercontent.com/assets/6333963/13198954/df000266-d7e4-11e5-9f5e-3cea3ca857a5.png">
<img width="603" alt="screen shot 2016-02-20 at 3 15 20 pm" src="https://cloud.githubusercontent.com/assets/6333963/13198953/deffbf22-d7e4-11e5-9fc4-cb8694802380.png">

**Comment by sky-bones** [comment]
(honestly jamie yr the only person who can probably do this - let me know if you need help finding shit or testing stuff)

**Comment by valeriebordeleau** [comment]
Is it possible to do this similarly to how we made the panel nav in class? just moving it to the next position? If not Im sure there's a sample we could work from on codepen

**Comment by sky-bones** [comment]
I found a codepen!! It looks like what we want to do. 

http://codepen.io/redfrost/pen/mzHjb

**Comment by jamie-smith8** [comment]
I can work with that

GOD BLESS YOU <3

**Comment by jamie-smith8** [comment]
http://codepen.io/dp_lewis/pen/hqylE 

but something with just css

**Comment by sky-bones** [comment]
I like that!! Whatever's easier to work with will be the best :)

**Comment by jamie-smith8** [comment]
done.
