### ISSUE TITLE
Login / Confirmation 

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#9]
- [x] Benefits section  
- [x] Sign In
- [x] Form 
- [x] Sign Up
- [x] Confirmation page 

Resources: 
https://learn-the-web.algonquindesign.ca/topics/forms/
https://learn-the-web.algonquindesign.ca/topics/forms-cheat-sheet/

**Comment by heathermcd12** [comment]
I will do the confirmation page!

**Comment by jazdown** [comment]
I'm doing the form and benefits section

**Comment by jamie-smith8** [comment]
can this be closed?

**Comment by sky-bones** [comment]
The confirmation page is finished, @jazdown is this completed?
